document: feedback-pipeline-workload
version: 1
data:
  name: binutils/annobin
  description: Set of packages that GCC depends on
  maintainer: sst_pt_gcc
  packages:
    - binutils
    - binutils-devel
    - binutils-gold
    - annobin-annocheck
    - annobin-plugin-gcc
    # used by several sst_pt tools (libabigail, dwz, binutils, debugedit)
    - xxhash
    - xxhash-libs
    - xxhash-devel
  labels:
    - eln
    - c10s
